FROM nginx:1.29.0-alpine
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf


RUN mkdir -p /var/cache/nginx/client_temp && \
        mkdir -p /var/cache/nginx/proxy_temp && \
        mkdir -p /var/cache/nginx/fastcgi_temp && \
        mkdir -p /var/cache/nginx/uwsgi_temp && \
        mkdir -p /var/cache/nginx/scgi_temp && \
        chown -R roboshop:roboshop /var/cache/nginx && \
        chown -R roboshop:roboshop /etc/nginx/ && \
        chmod -R 755 /etc/nginx/ && \
        chown -R boshop:roboshopx /var/log/nginx

RUN mkdir -p /etc/nginx/ssl/ && \
    chown -R roboshop:roboshop /etc/nginx/ssl/ && \
    chmod -R 755 /etc/nginx/ssl/

RUN touch /var/run/nginx.pid && \
        chown -R roboshop:roboshop /var/run/nginx.pid /run/nginx.pid
COPY nginx.conf /etc/nginx/nginx.conf
COPY static /usr/share/nginx/html
USER nginx
CMD ["nginx", "-g", "daemon off;"]
# FROM nginx

# RUN rm -rf /usr/share/nginx/html/index.html
# RUN rm -rf /etc/nginx/nginx.conf
# RUN rm -rf /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/nginx.conf
# COPY static /usr/share/nginx/html

