FROM  python:3.9
WORKDIR /opt/server/
ENV CART_HOST="cart"\
    CART_PORT="8080"\
    USER_HOST="user"\
    USER_PORT="8080"\
    AMQP_HOST="rabbitmq"\
    AMQP_USER="roboshop"\
    AMQP_PASS="roboshop123"
COPY reuirements.txt .
COPY *.py .
COPY payment.ini .
RUN pip3 install -r requirements.txt
CMD ["uwsgi", "--ini", "payment.ini"]
