FROM node:20-alpine3.21 AS builder
WORKDIR /usr/server
COPY package.json .
COPY *.js .  
RUN npm install

FROM node:20-alpine3.21
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
ENV MONGO="true"\
    REDIS_URL="redis://redis:6379"\
    MONGO_URL="mongodb://mongodb:27017/users"
WORKDIR /opt/server
COPY --from=builder /opt/server /opt/servers
RUN  chown -R roboshop:roboshop  /opt/server
USER roboshop
CMD ["node","server.js"]
